import "@/lib/pdfFonts";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { ReactNode } from "react";
import { normalizeForPdf } from "@/lib/textNormalize";

const N = normalizeForPdf;

const DARK = "#111827";
const GRAY = "#6b7280";
const MUTED = "#9ca3af";
const LIGHT = "#e5e7eb";

const ACCENT = {
  blue:    { fg: "#2563eb", bg: "rgba(37, 99, 235, 0.12)" },
  rose:    { fg: "#e11d48", bg: "rgba(225, 29, 72, 0.12)" },
  slate:   { fg: "#475569", bg: "rgba(71, 85, 105, 0.12)" },
  emerald: { fg: "#059669", bg: "rgba(5, 150, 105, 0.12)" },
  violet:  { fg: "#7c3aed", bg: "rgba(124, 58, 237, 0.12)" },
  amber:   { fg: "#d97706", bg: "rgba(217, 119, 6, 0.12)" },
} as const;

export type AccentKey = keyof typeof ACCENT;

const s = StyleSheet.create({
  page: { paddingTop: 50, paddingBottom: 56, paddingHorizontal: 36, fontFamily: "Inter", fontSize: 11, lineHeight: 1.5, color: DARK },
  festivalName: { fontSize: 22, fontWeight: 700 },
  festivalDates: { fontSize: 13, color: GRAY, marginTop: 4 },
  headerRow: { flexDirection: "row", alignItems: "center", marginTop: 28, marginBottom: 6 },
  circle: { width: 32, height: 32, borderRadius: 16, alignItems: "center", justifyContent: "center", marginRight: 12 },
  circleDot: { width: 10, height: 10, borderRadius: 5 },
  reportTitle: { fontSize: 28, fontWeight: 700 },
  subtitle: { fontSize: 11, color: GRAY, marginLeft: 44, marginBottom: 14 },
  divider: { borderBottom: `0.5pt solid ${LIGHT}`, marginBottom: 18 },
  summaryBox: { borderWidth: 0.5, borderColor: LIGHT, borderRadius: 6, padding: 12, marginBottom: 18 },
  footer: {
    position: "absolute", bottom: 24, left: 36, right: 36,
    flexDirection: "row", borderTop: `0.5pt solid ${LIGHT}`, paddingTop: 6,
    fontSize: 8, color: MUTED,
  },
  footerLeft: { flex: 1, textAlign: "left" },
  footerCenter: { flex: 1, textAlign: "center" },
  footerRight: { flex: 1, textAlign: "right" },
  footerCredit: {
    position: "absolute", bottom: 12, left: 36, right: 36,
    fontSize: 7, color: MUTED, textAlign: "center",
  },
});

export interface ReportTemplateProps {
  festivalName: string;
  festivalDates: string;
  reportTitle: string;
  reportSubtitle?: string;
  accentColor: AccentKey;
  generatedAt?: Date;
  summary?: ReactNode;
  children: ReactNode;
}

const fmtCoverDate = (d: Date) =>
  d.toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

export function ReportTemplate({
  festivalName,
  festivalDates,
  reportTitle,
  reportSubtitle,
  accentColor,
  generatedAt,
  summary,
  children,
}: ReportTemplateProps) {
  const accent = ACCENT[accentColor];
  const gen = generatedAt ?? new Date();
  return (
    <Document title={`${festivalName} — ${reportTitle}`} author="Full Event Project">
      <Page size="A4" style={s.page}>
        {/* Header (page 1 prominent; on subsequent pages the same layout repeats only via new Pages) */}
        <Text style={[s.festivalName, { color: accent.fg }]}>{N(festivalName)}</Text>
        <Text style={s.festivalDates}>{N(festivalDates)}</Text>

        <View style={s.headerRow}>
          <View style={[s.circle, { backgroundColor: accent.bg }]}>
            <View style={[s.circleDot, { backgroundColor: accent.fg }]} />
          </View>
          <Text style={s.reportTitle}>{N(reportTitle)}</Text>
        </View>
        {reportSubtitle ? <Text style={s.subtitle}>{N(reportSubtitle)}</Text> : null}
        <View style={s.divider} />

        {summary ? <View style={s.summaryBox}>{summary}</View> : null}

        {children}

        <View style={s.footer} fixed>
          <Text style={s.footerLeft}>{N(festivalName)}</Text>
          <Text style={s.footerCenter}>{N(reportTitle)}</Text>
          <Text style={s.footerRight} render={({ pageNumber, totalPages }) => `Page ${pageNumber} / ${totalPages}`} />
        </View>
        <Text style={s.footerCredit} fixed>
          {N(`Generated by Full Event Project · ${fmtCoverDate(gen)}`)}
        </Text>
      </Page>
    </Document>
  );
}

// Re-export shared low-level styles so per-report bodies can compose
export const reportStyles = StyleSheet.create({
  h2: { fontSize: 14, fontWeight: 700, marginTop: 12, marginBottom: 6, color: DARK },
  h3: { fontSize: 12, fontWeight: 600, marginTop: 8, marginBottom: 4, color: DARK },
  body: { fontSize: 11, lineHeight: 1.5, color: DARK },
  small: { fontSize: 9.5, color: GRAY, lineHeight: 1.4 },
  meta: { fontSize: 9, color: GRAY },
  card: { borderWidth: 0.5, borderColor: LIGHT, borderRadius: 6, padding: 12, marginBottom: 12 },
  cardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "baseline", marginBottom: 6 },
  cardTitle: { fontSize: 14, fontWeight: 600 },
  statusText: { fontSize: 10, fontWeight: 700, letterSpacing: 0.5 },
  row: { flexDirection: "row", marginVertical: 1.5 },
  label: { width: 100, fontSize: 9, color: GRAY, textTransform: "uppercase", letterSpacing: 0.4 },
  value: { flex: 1, fontSize: 11 },
  bullet: { fontSize: 10, marginLeft: 12, marginVertical: 1.5, lineHeight: 1.35 },
  th: { flexDirection: "row", borderBottom: `0.5pt solid ${DARK}`, paddingBottom: 4, marginBottom: 4, fontSize: 9, fontWeight: 700 },
  tr: { flexDirection: "row", borderBottom: `0.25pt solid ${LIGHT}`, paddingVertical: 3, fontSize: 10 },
});

export const reportColors = {
  ok: "#059669",
  warn: "#e11d48",
  amber: "#d97706",
  gray: GRAY,
  muted: MUTED,
  light: LIGHT,
  dark: DARK,
};

export const fmtFilename = (slug: string, section: string, d?: Date) => {
  const dt = d ?? new Date();
  const y = dt.getFullYear();
  const m = String(dt.getMonth() + 1).padStart(2, "0");
  const day = String(dt.getDate()).padStart(2, "0");
  return `${slug}-${section}-${y}${m}${day}.pdf`;
};
