import "@/lib/pdfFonts";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { ReactNode } from "react";
import { normalizeForPdf } from "@/lib/textNormalize";

const N = normalizeForPdf;

const DARK = "#111827";
const GRAY = "#6b7280";
const MUTED = "#9ca3af";
const LIGHT = "#e5e7eb";

const ACCENT = {
  blue:    { fg: "#2563eb", bg: "rgba(37, 99, 235, 0.12)" },
  rose:    { fg: "#e11d48", bg: "rgba(225, 29, 72, 0.12)" },
  slate:   { fg: "#475569", bg: "rgba(71, 85, 105, 0.12)" },
  emerald: { fg: "#059669", bg: "rgba(5, 150, 105, 0.12)" },
  violet:  { fg: "#7c3aed", bg: "rgba(124, 58, 237, 0.12)" },
  amber:   { fg: "#d97706", bg: "rgba(217, 119, 6, 0.12)" },
} as const;

export type AccentKey = keyof typeof ACCENT;

const s = StyleSheet.create({
  page: { paddingTop: 50, paddingBottom: 56, paddingHorizontal: 36, fontFamily: "OpenSans", fontSize: 11, lineHeight: 1.5, color: DARK },
  festivalName: { fontSize: 22, fontWeight: 700 },
  festivalDates: { fontSize: 13, color: GRAY, marginTop: 4 },
  headerRow: { flexDirection: "row", alignItems: "center", marginTop: 28, marginBottom: 6 },
  accentDot: { width: 10, height: 10, borderRadius: 5, marginRight: 10 },
  reportTitle: { fontSize: 28, fontWeight: 700 },
  subtitle: { fontSize: 11, color: GRAY, marginTop: 4, marginBottom: 14 },
  divider: { borderBottomWidth: 0.5, borderBottomColor: LIGHT, marginBottom: 18 },
  summaryBox: { borderWidth: 0.5, borderColor: LIGHT, padding: 12, marginBottom: 18 },
  footer: {
    position: "absolute", bottom: 24, left: 36, right: 36,
    flexDirection: "row", borderTopWidth: 0.5, borderTopColor: LIGHT, paddingTop: 6,
    fontSize: 8, color: MUTED,
  },
  footerLeft: { flex: 1, textAlign: "left" },
  footerCenter: { flex: 1, textAlign: "center" },
  footerRight: { flex: 1, textAlign: "right" },
  footerCredit: {
    position: "absolute", bottom: 12, left: 36, right: 36,
    fontSize: 7, color: MUTED, textAlign: "center",
  },
});

export interface ReportTemplateProps {
  festivalName: string;
  festivalDates: string;
  reportTitle: string;
  reportSubtitle?: string;
  accentColor: AccentKey;
  generatedAt?: Date;
  summary?: ReactNode;
  children: ReactNode;
}

const fmtCoverDate = (d: Date) =>
  d.toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

export function ReportTemplate({
  festivalName,
  festivalDates,
  reportTitle,
  reportSubtitle,
  accentColor,
  generatedAt,
  summary,
  children,
}: ReportTemplateProps) {
  const accent = ACCENT[accentColor];
  const gen = generatedAt ?? new Date();
  return (
    <Document title={`${festivalName} — ${reportTitle}`} author="Full Event Project">
      <Page size="A4" style={s.page}>
        {/* Header (page 1 prominent; on subsequent pages the same layout repeats only via new Pages) */}
        <Text style={[s.festivalName, { color: accent.fg }]}>{N(festivalName)}</Text>
        <Text style={s.festivalDates}>{N(festivalDates)}</Text>

        <View style={s.headerRow}>
          <View style={[s.accentDot, { backgroundColor: accent.fg }]} />
          <Text style={s.reportTitle}>{N(reportTitle)}</Text>
        </View>
        {reportSubtitle ? <Text style={s.subtitle}>{N(reportSubtitle)}</Text> : null}
        <View style={s.divider} />

        {summary ? <View style={s.summaryBox}>{summary}</View> : null}

        {children}

        <View style={s.footer} fixed>
          <Text style={s.footerLeft}>{N(festivalName)}</Text>
          <Text style={s.footerCenter}>{N(reportTitle)}</Text>
          <Text style={s.footerRight} render={({ pageNumber, totalPages }) => `Page ${pageNumber} / ${totalPages}`} />
        </View>
        <Text style={s.footerCredit} fixed>
          {N(`Generated by Full Event Project · ${fmtCoverDate(gen)}`)}
        </Text>
      </Page>
    </Document>
  );
}

// Re-export shared low-level styles so per-report bodies can compose
export const reportStyles = StyleSheet.create({
  h2: { fontSize: 14, fontWeight: 700, marginTop: 12, marginBottom: 6, color: DARK },
  h3: { fontSize: 12, fontWeight: 600, marginTop: 8, marginBottom: 4, color: DARK },
  body: { fontSize: 11, lineHeight: 1.5, color: DARK },
  small: { fontSize: 9.5, color: GRAY, lineHeight: 1.4 },
  meta: { fontSize: 9, color: GRAY },
  card: { borderWidth: 0.5, borderColor: LIGHT, borderRadius: 6, padding: 12, marginBottom: 12 },
  cardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "baseline", marginBottom: 6 },
  cardTitle: { fontSize: 14, fontWeight: 600 },
  statusText: { fontSize: 10, fontWeight: 700, letterSpacing: 0.5 },
  row: { flexDirection: "row", marginVertical: 1.5 },
  label: { width: 100, fontSize: 9, color: GRAY, textTransform: "uppercase", letterSpacing: 0.4 },
  value: { flex: 1, fontSize: 11 },
  bullet: { fontSize: 10, marginLeft: 12, marginVertical: 1.5, lineHeight: 1.35 },
  th: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: DARK, paddingBottom: 4, marginBottom: 4, fontSize: 9, fontWeight: 700 },
  tr: { flexDirection: "row", borderBottomWidth: 0.25, borderBottomColor: LIGHT, paddingVertical: 3, fontSize: 10 },
});

/* ============================================================================
   Shared table + section primitives
   Use these across every export to get consistent grid layout and safe
   pagination. `Section` puts its title on a fresh page after the first one.
   `Table` renders a header + row grid using flex weights per column.
   ============================================================================ */

export type TableColumn<T> = {
  header: string;
  /** Flex weight for the column (relative). Defaults to 1. */
  flex?: number;
  /** Cell renderer. Return a string, number, or a react-pdf primitive. */
  cell: (row: T, index: number) => import("react").ReactNode;
  /** Optional alignment. */
  align?: "left" | "right" | "center";
  /** Monospace-friendly (used for numeric columns). */
  mono?: boolean;
};

/** A row that spans every column, drawn as a full-width category header band. */
export type TableGroupRow = { __group: true; label: string; meta?: string };
/** A data row (any shape). */
export type TableDataRow<T> = { __group?: false } & T;
export type TableRow<T> = TableGroupRow | TableDataRow<T>;

const ZEBRA_BG = "#f7f8fa";
const HEADER_BG = "#f1f2f4";
const GROUP_BG = "#eef1f6";
const BORDER = "#d8dbe0";

const tableStyles = StyleSheet.create({
  // NOTE: no borderRadius / borderWidth on the wrap — react-pdf's border-clip
  // math overflows (`unsupported number: -9.7e+21` in clipBorderTop) when a
  // bordered+rounded container is split across pages with wrap={false} rows.
  // Borders live on the rows themselves.
  wrap: { marginBottom: 8 },
  th: {
    flexDirection: "row",
    backgroundColor: HEADER_BG,
    borderTopWidth: 0.5,
    borderTopColor: BORDER,
    borderBottomWidth: 0.75,
    borderBottomColor: DARK,
    paddingVertical: 5,
    paddingHorizontal: 6,
    fontSize: 8.5,
    fontWeight: 700,
    color: DARK,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  tr: {
    flexDirection: "row",
    borderBottomWidth: 0.25,
    borderBottomColor: BORDER,
    paddingVertical: 4,
    paddingHorizontal: 6,
    fontSize: 10,
    color: DARK,
  },
  trZebra: { backgroundColor: ZEBRA_BG },
  groupRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: GROUP_BG,
    borderTopWidth: 0.5,
    borderTopColor: BORDER,
    borderBottomWidth: 0.5,
    borderBottomColor: BORDER,
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  groupLabel: { fontSize: 10, fontWeight: 700, color: DARK, textTransform: "uppercase", letterSpacing: 0.5 },
  groupMeta: { fontSize: 9, color: GRAY },
  cellText: { fontSize: 10, color: DARK },
  cellMono: { fontSize: 10, color: DARK, fontFamily: "OpenSans" },
});

function isGroup<T>(r: TableRow<T>): r is TableGroupRow {
  return (r as TableGroupRow).__group === true;
}

export function Table<T>({
  columns,
  rows,
  emptyLabel = "No data",
  zebra = true,
}: {
  columns: TableColumn<T>[];
  rows: TableRow<T>[];
  emptyLabel?: string;
  zebra?: boolean;
}) {
  if (rows.length === 0) {
    return <Text style={{ fontSize: 10, color: GRAY }}>{emptyLabel}</Text>;
  }
  let dataIdx = -1;
  return (
    <View style={tableStyles.wrap}>
      <View style={tableStyles.th}>
{/* NOTE: `fixed` cannot be used on nested Views — it only works on direct
    children of Page. Applying it here caused clipBorderTop to receive
    massively negative coords and threw `unsupported number` at render. */}
        {columns.map((col, i) => (
          <Text
            key={i}
            style={{
              flex: col.flex ?? 1,
              textAlign: col.align ?? "left",
              paddingRight: 6,
            }}
          >
            {N(col.header)}
          </Text>
        ))}
      </View>
      {rows.map((row, ri) => {
        if (isGroup(row)) {
          return (
            <View key={ri} style={tableStyles.groupRow} wrap={false}>
              <Text style={tableStyles.groupLabel}>{N(row.label)}</Text>
              {row.meta ? <Text style={tableStyles.groupMeta}>{N(row.meta)}</Text> : null}
            </View>
          );
        }

        dataIdx += 1;
        const striped = zebra && dataIdx % 2 === 1;
        return (
          <View
            key={ri}
            style={[tableStyles.tr, striped ? tableStyles.trZebra : null] as any}
            wrap={false}
          >
            {columns.map((col, ci) => {
              const raw = col.cell(row as TableDataRow<T>, dataIdx);
              const node =
                typeof raw === "string" || typeof raw === "number" ? (
                  <Text style={col.mono ? tableStyles.cellMono : tableStyles.cellText}>
                    {N(String(raw))}
                  </Text>
                ) : (
                  raw
                );
              return (
                <View
                  key={ci}
                  style={{
                    flex: col.flex ?? 1,
                    paddingRight: 6,
                    alignItems:
                      col.align === "right"
                        ? "flex-end"
                        : col.align === "center"
                          ? "center"
                          : "flex-start",
                  }}
                >
                  {node}
                </View>
              );
            })}
          </View>
        );
      })}
    </View>
  );
}

/* ----- Reusable cell primitives ---------------------------------------- */

const badgeStyles = StyleSheet.create({
  base: {
    fontSize: 8.5,
    fontWeight: 700,
    paddingHorizontal: 5,
    paddingVertical: 1,
    // No borderRadius: react-pdf's border-radius clip math can overflow
    // (`unsupported number` in clipBorderTop) when a rounded Text sits in a
    // wrap={false} row near a page break. Keep it as a flat pill.
    textAlign: "center",
    letterSpacing: 0.3,
  },
  soborg:   { color: "#1d4ed8", backgroundColor: "#dbeafe" },
  onsite:   { color: "#047857", backgroundColor: "#d1fae5" },
  neutral:  { color: "#374151", backgroundColor: "#e5e7eb" },
  warn:     { color: "#b45309", backgroundColor: "#fef3c7" },
});

export function LoadBadge({ soborg }: { soborg: boolean }) {
  return (
    <Text style={[badgeStyles.base, soborg ? badgeStyles.soborg : badgeStyles.onsite]}>
      {soborg ? "SØBORG" : "ON-SITE"}
    </Text>
  );
}

export function Badge({ text, tone = "neutral" }: { text: string; tone?: "soborg" | "onsite" | "neutral" | "warn" }) {
  return <Text style={[badgeStyles.base, badgeStyles[tone]]}>{N(text)}</Text>;
}

const sectionStyles = StyleSheet.create({
  wrap: { marginBottom: 14 },
  header: {
    borderBottomWidth: 0.5,
    borderBottomColor: LIGHT,
    paddingBottom: 6,
    marginBottom: 8,
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "baseline",
  },
  title: { fontSize: 18, fontWeight: 700, color: DARK },
  meta: { fontSize: 9.5, color: GRAY },
  statsRow: { flexDirection: "row", flexWrap: "wrap", marginTop: 6 },
  statPill: {
    flexDirection: "row",
    alignItems: "baseline",
    backgroundColor: "#f1f2f4",
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginRight: 6,
    marginBottom: 2,
  },
  statValue: { fontSize: 10, fontWeight: 700, color: DARK },
  statLabel: { fontSize: 8.5, color: GRAY, marginLeft: 4, textTransform: "uppercase", letterSpacing: 0.4 },
});

export type SectionStat = { label: string; value: string | number };

export function Section({
  title,
  meta,
  stats,
  breakBefore = false,
  children,
}: {
  title: string;
  meta?: string;
  /** Small labeled pills rendered under the title (preferred over `meta`). */
  stats?: SectionStat[];
  /** Force a page break before this section. Use for entries after the first. */
  breakBefore?: boolean;
  children: import("react").ReactNode;
}) {
  return (
    <View style={sectionStyles.wrap} break={breakBefore}>
      <View style={sectionStyles.header}>
        <View style={sectionStyles.titleRow}>
          <Text style={sectionStyles.title}>{N(title)}</Text>
          {meta && !stats ? <Text style={sectionStyles.meta}>{N(meta)}</Text> : null}
        </View>
        {stats && stats.length ? (
          <View style={sectionStyles.statsRow}>
            {stats.map((st, i) => (
              <View key={i} style={sectionStyles.statPill}>
                <Text style={sectionStyles.statValue}>{N(String(st.value))}</Text>
                <Text style={sectionStyles.statLabel}>{N(st.label)}</Text>
              </View>
            ))}
          </View>
        ) : null}
      </View>
      {children}
    </View>
  );
}


export const reportColors = {
  ok: "#059669",
  warn: "#e11d48",
  amber: "#d97706",
  gray: GRAY,
  muted: MUTED,
  light: LIGHT,
  dark: DARK,
};

export const fmtFilename = (slug: string, section: string, d?: Date) => {
  const dt = d ?? new Date();
  const y = dt.getFullYear();
  const m = String(dt.getMonth() + 1).padStart(2, "0");
  const day = String(dt.getDate()).padStart(2, "0");
  return `${slug}-${section}-${y}${m}${day}.pdf`;
};
