// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-festivals.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_festivals_default = defineTool({
  name: "list_festivals",
  title: "List festivals",
  description: "List festivals visible to the signed-in user, ordered by start date.",
  inputSchema: {
    year: z.number().int().optional().describe("Filter by year (e.g. 2026)"),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("festivals").select("id, slug, name, city, year, setup_date, breakdown_date, is_active").order("setup_date", { ascending: true }).limit(limit ?? 25);
    if (year) q = q.eq("year", year);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { festivals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-festival.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.101.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_festival_default = defineTool2({
  name: "get_festival",
  title: "Get festival details",
  description: "Get a festival's details including contracts, concepts and staff counts. Look up by slug (preferred) or id.",
  inputSchema: {
    slug: z2.string().optional().describe("Festival slug, e.g. 'gron-tarnby-16-2026'"),
    id: z2.string().uuid().optional().describe("Festival UUID")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug, id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!slug && !id) {
      return { content: [{ type: "text", text: "Provide slug or id" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    let fq = sb.from("festivals").select("*").limit(1);
    if (slug) fq = fq.eq("slug", slug);
    else fq = fq.eq("id", id);
    const { data: festival, error } = await fq.maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!festival) return { content: [{ type: "text", text: "Festival not found" }], isError: true };
    const [{ data: contracts }, { data: concepts }, { count: staffCount }] = await Promise.all([
      sb.from("festival_contracts").select("id, alias, concept_id").eq("festival_id", festival.id),
      sb.from("festival_concepts").select("id, name").eq("festival_id", festival.id),
      sb.from("festival_staff").select("id", { count: "exact", head: true }).eq("festival_id", festival.id)
    ]);
    const payload = {
      festival,
      contracts: contracts ?? [],
      concepts: concepts ?? [],
      staff_count: staffCount ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-festival-staff.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.101.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_festival_staff_default = defineTool3({
  name: "list_festival_staff",
  title: "List festival staff",
  description: "List staff assigned to a festival, optionally filtered by contract alias (e.g. 'Fish 1').",
  inputSchema: {
    festival_id: z3.string().uuid().describe("Festival UUID"),
    contract_alias: z3.string().optional().describe("Filter to one contract group by alias, e.g. 'Fish 1', 'Gyros 2'")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ festival_id, contract_alias }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let contractId = null;
    if (contract_alias) {
      const { data: contract } = await sb.from("festival_contracts").select("id").eq("festival_id", festival_id).eq("alias", contract_alias).maybeSingle();
      if (!contract) {
        return {
          content: [{ type: "text", text: `No contract with alias '${contract_alias}' for festival` }],
          isError: true
        };
      }
      contractId = contract.id;
    }
    let q = sb.from("festival_staff").select("id, staff_number, full_name, role, phone, wristband_type, contract_id, concept_id").eq("festival_id", festival_id).order("staff_number", { ascending: true });
    if (contractId) q = q.eq("contract_id", contractId);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { staff: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "llnmwiyvsmbnzqqhokjo";
var mcp_default = defineMcp({
  name: "full-event-project-mcp",
  title: "Full Event Project MCP",
  version: "0.1.0",
  instructions: "Tools for the Full Event Project festival operations app. Use `list_festivals` to discover festivals, `get_festival` for details, and `list_festival_staff` (optionally by contract alias like 'Fish 1') to inspect crew.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_festivals_default, get_festival_default, list_festival_staff_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
